export const exportTables = [
  { key: "users", label: "Utenti", category: "Anagrafica" },
  { key: "doctors", label: "Medici", category: "Anagrafica" },
  { key: "doctorAvailabilityWindows", label: "Orari medici", category: "Sistema" },
  { key: "doctorTimeOffs", label: "Assenze medici", category: "Agenda" },
  { key: "patients", label: "Pazienti", category: "Anagrafica" },
  { key: "consentModules", label: "Moduli consenso", category: "Sistema" },
  { key: "patientConsents", label: "Consensi pazienti", category: "Anagrafica" },
  { key: "appointments", label: "Appuntamenti", category: "Agenda" },
  { key: "appointmentReminderRules", label: "Regole promemoria", category: "Sistema" },
  { key: "appointmentReminders", label: "Log promemoria", category: "Agenda" },
  { key: "clinicalNotes", label: "Note cliniche", category: "Clinica" },
  { key: "dentalRecords", label: "Cartella clinica", category: "Clinica" },
  { key: "smsTemplates", label: "Template SMS", category: "Sistema" },
  { key: "smsLogs", label: "Log SMS", category: "Sistema" },
  { key: "smsProviderConfig", label: "Config ClickSend", category: "Configurazione" },
  { key: "wacomConfig", label: "Config Wacom", category: "Configurazione" },
  { key: "kapsoWhatsAppConfig", label: "Config WhatsApp Kapso", category: "Configurazione" },
  { key: "emailTemplates", label: "Template email", category: "Sistema" },
  { key: "dailyReminderConfig", label: "Config promemoria quotidiano", category: "Configurazione" },
  { key: "dailyReminderLogs", label: "Log promemoria quotidiano", category: "Sistema" },
  { key: "practiceWeeklyReportConfig", label: "Config report settimanale", category: "Configurazione" },
  { key: "practiceWeeklyReportLogs", label: "Log report settimanale", category: "Sistema" },
  { key: "recurringMessageConfigs", label: "Config messaggi ricorrenti", category: "Configurazione" },
  { key: "recurringMessageLogs", label: "Log messaggi ricorrenti", category: "Sistema" },
  { key: "practiceSettings", label: "Impostazioni clinica", category: "Configurazione" },
  { key: "practiceClosures", label: "Chiusure (ferie/permessi)", category: "Agenda" },
  { key: "practiceWeeklyClosures", label: "Chiusure settimanali", category: "Agenda" },
  { key: "auditLogs", label: "Audit log", category: "Sistema" },
  { key: "suppliers", label: "Fornitori", category: "Magazzino" },
  { key: "products", label: "Prodotti", category: "Magazzino" },
  { key: "services", label: "Prestazioni", category: "Configurazione" },
  { key: "stockMovements", label: "Movimenti magazzino", category: "Magazzino" },
  { key: "financeEntries", label: "Finanza", category: "Amministrazione" },
  { key: "patientPayments", label: "Pagamenti pazienti", category: "Amministrazione" },
  { key: "quickNotesPaymentSync", label: "Sync pagamenti QuickNotes", category: "Amministrazione" },
  { key: "cashAdvances", label: "Anticipi", category: "Amministrazione" },
  { key: "recallRules", label: "Regole richiami", category: "Sistema" },
  { key: "recalls", label: "Richiami", category: "Agenda" },
  { key: "quotes", label: "Preventivi", category: "Amministrazione" },
  { key: "quoteItems", label: "Righe preventivo", category: "Amministrazione" },
  { key: "medicalCertificates", label: "Certificati Medici", category: "Clinica" },
  { key: "anamnesisConditions", label: "Condizioni anamnesi", category: "Clinica" },
  { key: "featureUpdates", label: "Aggiornamenti sistema", category: "Sistema" },
  { key: "featureUpdateDismissals", label: "Dismissal aggiornamenti", category: "Sistema" },
  { key: "roleFeatureAccess", label: "Accesso funzionalità", category: "Configurazione" },
  { key: "userAwards", label: "Premi utenti", category: "Sistema" },
  { key: "featureInstructions", label: "Istruzioni funzionalità", category: "Sistema" },
  { key: "featureInstructionSteps", label: "Step istruzioni", category: "Sistema" },
  { key: "userInstructionProgress", label: "Progresso istruzioni", category: "Sistema" },
] as const;

export type ExportTableKey = (typeof exportTables)[number]["key"];
export const exportTableKeys = new Set<ExportTableKey>(exportTables.map((table) => table.key));
export const isExportTableKey = (value: string): value is ExportTableKey => exportTableKeys.has(value as ExportTableKey);
