import type { Metadata } from "next";

export function createPageMetadata(title: string): Metadata {
  return { title };
}

export const PAGE_TITLES = {
  giornata: "Giornata",
  agenda: "Agenda",
  appuntamenti: "Appuntamenti",
  calendario: "Calendario",
  pazienti: "Pazienti",
  listaPazienti: "Lista pazienti",
  nuovoPaziente: "Nuovo paziente",
  cercaDuplicati: "Cerca duplicati",
  richiami: "Richiami",
  regoleAutomatiche: "Regole automatiche",

  comunicazioniRicorrenti: "Comunicazioni ricorrenti",
  richiamiProgrammati: "Richiami programmati",
  magazzino: "Magazzino",
  fornitori: "Fornitori",
  prodotti: "Prodotti",
  impianti: "Impianti",
  movimenti: "Movimenti",
  listaProdotti: "Lista prodotti",
  listaMovimenti: "Lista movimenti",
  finanza: "Finanza",
  pagamenti: "Pagamenti",
  spese: "Spese",
  anticipi: "Anticipi",
  reportGiornaliero: "Report giornaliero",
  reportMensile: "Report mensile",
  reportUscite: "Report uscite",
  reportMedici: "Report medici",
  listaAppuntamenti: "Lista appuntamenti",
  profilo: "Profilo",
  medici: "Medici",
  amministrazione: "Amministrazione",
  elencoMedici: "Elenco medici",
  calendarioStudio: "Calendario studio",
  istruzioni: "Istruzioni funzionalità",
  aggiornamenti: "Popup funzionalità",
  messaggioBenvenuto: "Messaggio di Benvenuto",
  moduliConsenso: "Moduli consenso",
  messaggiEmail: "Messaggi email",
  reportSettimanale: "Report settimanale",
  anteprimaReportSettimanale: "Anteprima report settimanale",
  promemoriaQuotidiano: "Promemoria quotidiano",
  anteprimaPromemoriaQuotidiano: "Anteprima promemoria quotidiano",
  utenti: "Utenti sistema",
  accessoFunzionalita: "Accesso funzionalità",
  errori: "Errori sistema",
  audit: "Audit sistema",
  privacy: "Privacy e GDPR",
  authorizationTokens: "Authorization Tokens",
  servizi: "Servizi offerti",
  anamnesi: "Anamnesi",
  messaggiSms: "Messaggi SMS",
  clicksend: "Integrazione Clicksend",
  whatsapp: "Integrazione WhatsApp",
  scanid: "Integrazione Applicazione",
  wacom: "Integrazione Wacom",
  resetDatabase: "Reset database",
  modificaEmail: "Modifica email",
  documentazione: "Documentazione",
  accesso: "Accesso",
  contatti: "Contatti",
  termini: "Termini di servizio",
  areaStaff: "Area staff",
  preventivo: "Preventivo",
  stampaConsensi: "Stampa consensi",
  stampaDiario: "Stampa diario",
  stampaScheda: "Stampa scheda",
  consenso: "Consenso",
  certificati: "Certificati",
  nuovoCertificato: "Nuovo certificato",
  stampaCertificato: "Stampa certificato",
  pazienteNonTrovato: "Paziente non trovato",
  home: "SORRIDI",
} as const;
